In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = ['the glass of milk',
        'I am a good boy',
        'I am a good developer']

In [3]:
## Define the vocabulary size
voc_size = 10000

In [6]:
# One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9704, 1648, 9189, 9556],
 [1130, 4967, 7180, 3722, 40],
 [1130, 4967, 7180, 3722, 876]]

In [7]:
# Word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [10]:
print(embedded_docs)

[[   0    0    0    0 9704 1648 9189 9556]
 [   0    0    0 1130 4967 7180 3722   40]
 [   0    0    0 1130 4967 7180 3722  876]]


In [27]:
# feature representation
dim=10

In [44]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[ 0.00206987,  0.01799513, -0.03939884,  0.00152919,
          0.03774568, -0.04084804,  0.02523282, -0.04204376,
         -0.00940025,  0.01378592],
        [ 0.00206987,  0.01799513, -0.03939884,  0.00152919,
          0.03774568, -0.04084804,  0.02523282, -0.04204376,
         -0.00940025,  0.01378592],
        [ 0.00206987,  0.01799513, -0.03939884,  0.00152919,
          0.03774568, -0.04084804,  0.02523282, -0.04204376,
         -0.00940025,  0.01378592],
        [ 0.00206987,  0.01799513, -0.03939884,  0.00152919,
          0.03774568, -0.04084804,  0.02523282, -0.04204376,
         -0.00940025,  0.01378592],
        [ 0.0380807 ,  0.01587984, -0.00352602,  0.04037127,
         -0.04248517,  0.03267306, -0.01425955,  0.03826738,
          0.0200444 , -0.00100268],
        [ 0.03420955,  0.03888989,  0.04958173, -0.03497248,
          0.041064  ,  0.04588426,  0.04332181, -0.03249482,
          0.01112073, -0.0121806 ],
        [-0.02978129, -0.03529214, -0.04148177, -0.0

In [38]:
x = embedded_docs[0]

In [41]:
model.predict(x)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None